# Generated by Django 3.2.9 on 2022-02-16 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("social_network", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 12, 59, 28, 723203, tzinfo=utc),
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 12, 59, 28, 722646, tzinfo=utc),
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 12, 59, 28, 720872, tzinfo=utc),
            ),
        ),
    ]
