# Generated by Django 3.2.12 on 2022-02-09 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 9, 17, 27, 4, 438033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 9, 17, 27, 4, 437720, tzinfo=utc)),
        ),
    ]
