# Generated by Django 3.2.9 on 2022-02-16 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("social_network", "0002_auto_20220216_1259")]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 13, 24, 7, 229057, tzinfo=utc),
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 13, 24, 7, 228378, tzinfo=utc),
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 13, 24, 7, 226392, tzinfo=utc),
            ),
        ),
        migrations.AlterUniqueTogether(name="like", unique_together=set()),
    ]
