# Generated by Django 3.2.9 on 2022-02-16 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("social_network", "0003_auto_20220216_1324")]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 13, 31, 51, 829485, tzinfo=utc),
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 13, 31, 51, 829040, tzinfo=utc),
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 13, 31, 51, 826999, tzinfo=utc),
            ),
        ),
    ]
