# Generated by Django 3.2.12 on 2022-02-04 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_auto_20220204_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 4, 14, 50, 19, 357045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 4, 14, 50, 19, 356682, tzinfo=utc)),
        ),
    ]
