# Generated by Django 3.2.9 on 2022-02-16 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("social_network", "0004_auto_20220216_1331")]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 14, 34, 29, 116900, tzinfo=utc),
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 14, 34, 29, 116447, tzinfo=utc),
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 2, 16, 14, 34, 29, 114416, tzinfo=utc),
            ),
        ),
    ]
