# Generated by Django 3.2.12 on 2022-02-04 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_auto_20220204_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 4, 15, 9, 7, 50553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 4, 15, 9, 7, 50061, tzinfo=utc)),
        ),
    ]
